### ISSUE TITLE
Example from Readme errors

### ISSUE THREAD

**Issue by nilshg** [jmboehm/StataCall.jl#1]
Running the example from the readme I get:

```
julia> dfOut = StataCall.stataCall(instructions, df)
Error running Stata script. Printing log file:
ERROR: IOError: could not spawn `cat 'C:\Users\ngudat\AppData\Local\Julia-1.2.0\__63740167563080.log'`: no such file or directory (ENOENT)
```

Any idea what could cause this?

**Comment by jmboehm** [comment]
Hmmm... try to run it from the command line and see whether it works on a different file. Are you on Windows?

I believe the package hasn't been used much by others yet, so it's likely that there are some bugs in there that just happen to not show up for my use cases.

**Comment by jmboehm** [comment]
The examples should be working now (at least the tests pass on my osx machine and on my windows machine with buildkite) and I've removed the use of `cat` (which doesn't work on windows). Please feel free to re-open if this is still an issue.
